---
title: "ISSS608VA Project Website"
description: |
  This is the project website for ISSS608 Visual Analytics and Applications 2021-2022 April Term, Group 9
site: distill::distill_website
---

Below is the summary of the project:

**Project Members:**

[HUANG ANNI](mailto:annihuang.2021@mitb.smu.edu.sg)

[NI JUNQIU](mailto:junqiu.ni.2021@mitb.smu.edu.sg)

[WANG TIANQI](mailto:tianqi.wang.2020@mitb.smu.edu.sg)



**Project Title:**

[VAST Challenge 2022](https://vast-challenge.github.io/2022/) - Challenge 1: Demographics and Relationships

**Project Description:**

*Motivation:* The purpose of the project is to help the city planning team of Engagement, Ohio USA to understand the current state of the city and identify opportunities for future growth through visual analytics of the data collected from the representative residents.

*Objectives:* We aim to use visual analytic techniques to address three main questions: to characterize demographics of the town, describe the patterns of social activities in the community, and identify the predominant business base of the town.

*Main features of the application:* The Shiny application will provides interactivity and effective integration of techniques from data analytics and data visualization. There will be 3 main sections in the application where users can adjust inputs/outputs to make informed choices and derive insights about the demographics, relationships and businesses of the town. 



