---
title: "Project Proposal"
description: |
  Project Proposal for ISSS608 Visual Analytics and Applications - Group 9
author:
  - name: Group9:<br> HUANG ANNI <br> NI JUNQIU <br> WANG TIANQI <br>
    #url: 
date: 2022-05-07
output:
  distill::distill_article:
    self_contained: false
    toc: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1. Overview

In this project, our team will try on building web-enabled visual analytics application by using R Shiny. The project aims to democratize data and analytics. The application will focus and emphasize on interactivity and effective integration of techniques from data analytics and data visualization.

# 2. Project Topic

The topic of Visual Analytics Project will be based on [VAST Challenge 2022](https://vast-challenge.github.io/2022/). Our team will choose Challenge 1 and build a Shiny Application to answer the questions of the Challenge. Challenge 1 is to understand the city’s demographics and relationships. We will analyse the available data about the social networks and other information of the city to learn about the city’s demographics, its neighborhoods, and its business base.

# 3. Motivation 

The purpose of the project is to help the city planning team of Engagement, Ohio USA to understand the current state of the city and identify opportunities for future growth. The visual analytics exercise can use related visual analytic techniques to analyse the data collected from the representative residents using the city’s urban planning app.


# 4. Problems and Issues

In this project, we will solve three main problems of Challenge 1. First, assuming the volunteers are representative of the city’s population, we will characterize the demographics of the town. Also, considering  the social activities in the community, we will describe the patterns in the social networks in the town. Lastly, we will identify the predominant business base of the town, and describe patterns we observe. 


# 5. Related Work and Approach

XXXX


# 6. Storyboards and Prototypes

XXXX


